Capstone Project/Controllers/MonthlyFinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Capstone_Project.Data;
using Capstone_Project.Models;

namespace Capstone_Project.Controllers
{
    public class MonthlyFinanceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MonthlyFinanceController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MonthlyFinance
        public async Task<IActionResult> Index()
        {
            return View(await _context.Finance.ToListAsync());
        }

        // GET: MonthlyFinance/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyFinance = await _context.Finance
                .FirstOrDefaultAsync(m => m.Id == id);
            if (monthlyFinance == null)
            {
                return NotFound();
            }

            return View(monthlyFinance);
        }

        // GET: MonthlyFinance/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MonthlyFinance/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Item,Date,Amount,Type")] MonthlyFinance monthlyFinance)
        {
            if (ModelState.IsValid)
            {
                _context.Add(monthlyFinance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(monthlyFinance);
        }

        // GET: MonthlyFinance/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyFinance = await _context.Finance.FindAsync(id);
            if (monthlyFinance == null)
            {
                return NotFound();
            }
            return View(monthlyFinance);
        }

        // POST: MonthlyFinance/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Item,Date,Amount,Type")] MonthlyFinance monthlyFinance)
        {
            if (id != monthlyFinance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(monthlyFinance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonthlyFinanceExists(monthlyFinance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(monthlyFinance);
        }

        // GET: MonthlyFinance/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monthlyFinance = await _context.Finance
                .FirstOrDefaultAsync(m => m.Id == id);
            if (monthlyFinance == null)
            {
                return NotFound();
            }

            return View(monthlyFinance);
        }

        // POST: MonthlyFinance/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var monthlyFinance = await _context.Finance.FindAsync(id);
            _context.Finance.Remove(monthlyFinance);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonthlyFinanceExists(int id)
        {
            return _context.Finance.Any(e => e.Id == id);
        }
    }
}

Capstone Project/Controllers/NewGoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Capstone_Project.Data;
using Capstone_Project.Models;

namespace Capstone_Project.Controllers
{
    public class NewGoalController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NewGoalController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NewGoal
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewGoal.ToListAsync());
        }

        // GET: NewGoal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newGoal = await _context.NewGoal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newGoal == null)
            {
                return NotFound();
            }

            return View(newGoal);
        }

        // GET: NewGoal/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewGoal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Goal,Amount,Monthly")] NewGoal newGoal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newGoal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newGoal);
        }

        // GET: NewGoal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newGoal = await _context.NewGoal.FindAsync(id);
            if (newGoal == null)
            {
                return NotFound();
            }
            return View(newGoal);
        }

        // POST: NewGoal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Goal,Amount,Monthly")] NewGoal newGoal)
        {
            if (id != newGoal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newGoal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewGoalExists(newGoal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newGoal);
        }

        // GET: NewGoal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newGoal = await _context.NewGoal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newGoal == null)
            {
                return NotFound();
            }

            return View(newGoal);
        }

        // POST: NewGoal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newGoal = await _context.NewGoal.FindAsync(id);
            _context.NewGoal.Remove(newGoal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewGoalExists(int id)
        {
            return _context.NewGoal.Any(e => e.Id == id);
        }
    }
}

Capstone Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Budget Pro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>


    <style>

        body {
            background-image: url("https://i.ibb.co/VDfxjJx/background-7.jpg");
            background-repeat: no-repeat;
            background-size: 100%;
        }
    </style>




<body>

    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Guide">Budgeting Guide </a>

                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MonthlyFinance" asp-action="Create">Create/Manage Budget</a>

                        </li>
                        <li class"nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewGoal" asp-action="Create">Add A Goal</a>

                        </li>






                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

   



</body>
</html>